const buttonColorToken = {
  colorBackgroundButtonPrimary: 'B400',
  colorBackgroundButtonPrimaryHover: 'B500',
  colorBackgroundButtonPrimaryActive: 'B600',
  colorBackgroundButtonPrimaryFocused: 'B500',
  colorBackgroundButtonPrimaryDisabled: 'B200',
  colorTextButtonPrimary: 'N0',
  colorTextButtonPrimaryHover: 'N0',
  colorTextButtonPrimaryActive: 'N0',
  colorTextButtonPrimaryFocused: 'N0',
  colorTextButtonPrimaryDisabled: 'N0',

  colorBackgroundButtonSecondary: 'N0',
  colorBackgroundButtonSecondaryHover: 'N0',
  colorBackgroundButtonSecondaryActive: 'N100',
  colorBackgroundButtonSecondaryFocused: 'N0',
  colorBackgroundButtonSecondaryDisabled: 'N0',
  colorTextButtonSecondary: 'N700',
  colorTextButtonSecondaryHover: 'N800',
  colorTextButtonSecondaryActive: 'N800',
  colorTextButtonSecondaryFocused: 'N800',
  colorTextButtonSecondaryDisabled: 'N500',
  colorBorderButtonSecondary: 'N400',
  colorBorderButtonSecondaryHover: 'N600',
  colorBorderButtonSecondaryActive: 'N500',
  colorBorderButtonSecondaryFocused: 'N500',
  colorBorderButtonSecondaryDisabled: 'N300',

  colorBackgroundButtonMinimal: 'transparent',
  colorBackgroundButtonMinimalHover: 'N100',
  colorBackgroundButtonMinimalActive: 'N200',
  colorBackgroundButtonMinimalFocused: 'N50',
  colorBackgroundButtonMinimalDisabled: 'transparent',
  colorTextButtonMinimal: 'N700',
  colorTextButtonMinimalHover: 'N800',
  colorTextButtonMinimalActive: 'N800',
  colorTextButtonMinimalFocused: 'N700',
  colorTextButtonMinimalDisabled: 'N400',

  colorBackgroundButtonError: 'R400',
  colorBackgroundButtonErrorHover: 'R500',
  colorBackgroundButtonErrorActive: 'R600',
  colorBackgroundButtonErrorFocused: 'R500',
  colorBackgroundButtonErrorDisabled: 'R100',
  colorTextButtonError: 'N0',
  colorTextButtonErrorHover: 'N0',
  colorTextButtonErrorActive: 'N0',
  colorTextButtonErrorFocused: 'N0',
  colorTextButtonErrorDisabled: 'N0',
};

export default {
  ...buttonColorToken,
};
