const buttonToken = {
  colorBackgroundButtonPrimary: "B400",
  colorBackgroundButtonPrimaryHover: "B500",
  colorBackgroundButtonPrimaryActive: "B600",
  colorBackgroundButtonPrimaryFocused: "B500",
  colorBackgroundButtonPrimaryDisabled: "B200",
  colorTextButtonPrimary: "N0",
  colorTextButtonPrimaryHover: "N0",
  colorTextButtonPrimaryActive: "N0",
  colorTextButtonPrimaryFocused: "N0",
  colorTextButtonPrimaryDisabled: "N0",

  colorBackgroundButtonFillSecondary: "N100",
  colorBackgroundButtonFillSecondaryHover: "N200",
  colorBackgroundButtonFillSecondaryActive: "N300",
  colorBackgroundButtonFillSecondaryFocused: "N100",
  colorBackgroundButtonFillSecondaryDisabled: "N100",
  colorTextButtonFillSecondary: "N600",
  colorTextButtonFillSecondaryHover: "N800",
  colorTextButtonFillSecondaryActive: "N800",
  colorTextButtonFillSecondaryFocused: "N800",
  colorTextButtonFillSecondaryDisabled: "N400",

  colorBackgroundButtonTertiary: "B50",
  colorBackgroundButtonTertiaryHover: "B100",
  colorBackgroundButtonTertiaryActive: "B200",
  colorBackgroundButtonTertiaryFocused: "B100",
  colorBackgroundButtonTertiaryDisabled: "B50",
  colorTextButtonTertiary: "B400",
  colorTextButtonTertiaryHover: "B500",
  colorTextButtonTertiaryActive: "B500",
  colorTextButtonTertiaryFocused: "B500",
  colorTextButtonTertiaryDisabled: "B200",

  colorBackgroundButtonSecondary: "N0",
  colorBackgroundButtonSecondaryHover: "N0",
  colorBackgroundButtonSecondaryActive: "N100",
  colorBackgroundButtonSecondaryFocused: "N0",
  colorBackgroundButtonSecondaryDisabled: "N0",
  colorTextButtonSecondary: "N600",
  colorTextButtonSecondaryHover: "N800",
  colorTextButtonSecondaryActive: "N800",
  colorTextButtonSecondaryFocused: "N800",
  colorTextButtonSecondaryDisabled: "N500",
  colorBorderButtonSecondary: "N400",
  colorBorderButtonSecondaryHover: "N600",
  colorBorderButtonSecondaryActive: "N500",
  colorBorderButtonSecondaryFocused: "N500",
  colorBorderButtonSecondaryDisabled: "N300",

  colorBackgroundButtonSecondaryColored: "N0",
  colorBackgroundButtonSecondaryColoredHover: "N0",
  colorBackgroundButtonSecondaryColoredActive: "B100",
  colorBackgroundButtonSecondaryColoredFocused: "N0",
  colorBackgroundButtonSecondaryColoredDisabled: "N0",
  colorTextButtonSecondaryColored: "B400",
  colorTextButtonSecondaryColoredHover: "B600",
  colorTextButtonSecondaryColoredActive: "B600",
  colorTextButtonSecondaryColoredFocused: "B600",
  colorTextButtonSecondaryColoredDisabled: "B200",
  colorBorderButtonSecondaryColored: "B400",
  colorBorderButtonSecondaryColoredHover: "B600",
  colorBorderButtonSecondaryColoredActive: "B500",
  colorBorderButtonSecondaryColoredFocused: "B500",
  colorBorderButtonSecondaryColoredDisabled: "B100",

  colorBackgroundButtonMinimal: "transparent",
  colorBackgroundButtonMinimalHover: "N100",
  colorBackgroundButtonMinimalActive: "N200",
  colorBackgroundButtonMinimalFocused: "N50",
  colorBackgroundButtonMinimalDisabled: "transparent",
  colorTextButtonMinimal: "N600",
  colorTextButtonMinimalHover: "N800",
  colorTextButtonMinimalActive: "N800",
  colorTextButtonMinimalFocused: "N700",
  colorTextButtonMinimalDisabled: "N400",

  colorBackgroundButtonMinimalColored: "transparent",
  colorBackgroundButtonMinimalColoredHover: "B100",
  colorBackgroundButtonMinimalColoredActive: "B200",
  colorBackgroundButtonMinimalColoredFocused: "B50",
  colorBackgroundButtonMinimalColoredDisabled: "transparent",
  colorTextButtonMinimalColored: "B400",
  colorTextButtonMinimalColoredHover: "B600",
  colorTextButtonMinimalColoredActive: "B600",
  colorTextButtonMinimalColoredFocused: "B600",
  colorTextButtonMinimalColoredDisabled: "B200",

  colorBackgroundButtonError: "R400",
  colorBackgroundButtonErrorHover: "R500",
  colorBackgroundButtonErrorActive: "R600",
  colorBackgroundButtonErrorFocused: "R500",
  colorBackgroundButtonErrorDisabled: "R100",
  colorTextButtonError: "N0",
  colorTextButtonErrorHover: "N0",
  colorTextButtonErrorActive: "N0",
  colorTextButtonErrorFocused: "N0",
  colorTextButtonErrorDisabled: "N0",

  colorBorderButtonOptionFocused: "B200",
  colorBackgroundButtonOptionSelected: "B50",
  colorTextButtonOptionSelected: "B400",
};

export default buttonToken;
