# Workflow name
name: "Chromatic"

on:
  push:
    paths:
      - apps/storybook/**
      - packages/**
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: install
        run: pnpm install

      - name: build
        run: pnpm build

      - name: Push Storybook to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: "apps/storybook/storybook-static"
